// Pivot — worked examples. Each one was checked against the planner.

export const EXAMPLES = [
  {
    id: 'front-door',
    title: 'Sofa vs. a narrow front door',
    blurb: 'An 81 cm door and a sofa 90 cm deep. Straight in is impossible — watch it hook round the frame on its end.',
    icon: 'it-sofa',
    item: { type: 'sofa', params: { W: 196, D: 90, H: 82, seatH: 44, armH: 60, armW: 18, backT: 20, legH: 12, legs: true } },
    route: [
      { t: 'door', w: 81, h: 210, d: 14 },
      { t: 'turn', dir: 'R', beyond: 30 },
      { t: 'hall', w: 110, l: 420, h: 250 },
      { t: 'turn', dir: 'L' },
      { t: 'door', w: 86, h: 210, d: 12 },
      { t: 'room', w: 380, l: 420, h: 260, name: 'Living room' },
    ],
  },
  {
    id: 'lift',
    title: 'Apartment sofa via the lift',
    blurb: 'Lobby, an 8-person lift and a corridor to the flat. It is too long to lie down in the car.',
    icon: 'st-lift',
    item: { type: 'sofa', params: { W: 184, D: 84, H: 78, seatH: 43, armH: 58, armW: 17, backT: 18, legH: 10, legs: true } },
    route: [
      { t: 'door', w: 120, h: 215, d: 20 },
      { t: 'hall', w: 220, l: 450, h: 290 },
      { t: 'lift', cw: 110, cd: 140, ch: 220, dw: 90, dh: 210, align: 'center', exit: 'same' },
      { t: 'turn', dir: 'L', beyond: 60 },
      { t: 'hall', w: 150, l: 480, h: 265 },
      { t: 'turn', dir: 'R' },
      { t: 'door', w: 91, h: 205, d: 16 },
      { t: 'room', w: 400, l: 450, h: 265, name: 'Living room' },
    ],
  },
  {
    id: 'friends',
    title: 'PIVOT! The stairwell',
    blurb: 'A long sofa, a narrow stairwell and a U-turn landing. Can anything save it?',
    icon: 'st-turn-UL',
    item: { type: 'sofa', params: { W: 213, D: 94, H: 86, seatH: 46, armH: 64, armW: 22, backT: 24, legH: 12, legs: true } },
    route: [
      { t: 'door', w: 91, h: 205, d: 14 },
      { t: 'hall', w: 110, l: 260, h: 250 },
      { t: 'stairs', dir: 'up', w: 92, n: 9, rise: 18, go: 26, head: 200, ceil: 'sloped' },
      { t: 'turn', dir: 'UL', divider: 'rail' },
      { t: 'stairs', dir: 'up', w: 92, n: 9, rise: 18, go: 26, head: 200, ceil: 'sloped' },
      { t: 'hall', w: 110, l: 220, h: 250 },
      { t: 'turn', dir: 'R' },
      { t: 'door', w: 81, h: 203, d: 14 },
      { t: 'room', w: 400, l: 420, h: 260, name: 'Apartment' },
    ],
  },
  {
    id: 'boxspring',
    title: 'Queen box spring upstairs',
    blurb: 'The item movers dread: a rigid 152 × 203 board, a low bulkhead and a turn at the top.',
    icon: 'it-boxspring',
    item: { type: 'boxspring', params: { W: 203, D: 152, H: 23 } },
    route: [
      { t: 'door', w: 91, h: 205, d: 14 },
      { t: 'hall', w: 105, l: 240, h: 250 },
      { t: 'stairs', dir: 'up', w: 90, n: 14, rise: 18.5, go: 25, head: 196, ceil: 'open' },
      { t: 'turn', dir: 'R' },
      { t: 'hall', w: 95, l: 320, h: 245 },
      { t: 'turn', dir: 'L' },
      { t: 'door', w: 76, h: 203, d: 12 },
      { t: 'room', w: 360, l: 380, h: 245, name: 'Bedroom' },
    ],
  },
  {
    id: 'fridge',
    title: 'Fridge into a galley kitchen',
    blurb: 'It has to stay upright, and the kitchen door is round a tight corner.',
    icon: 'it-fridge',
    item: { type: 'fridge', params: { W: 70, H: 178, D: 70, layDown: false } },
    route: [
      { t: 'door', w: 81, h: 203, d: 14 },
      { t: 'hall', w: 100, l: 260, h: 250 },
      { t: 'turn', dir: 'L' },
      { t: 'door', w: 76, h: 203, d: 12 },
      { t: 'room', w: 240, l: 360, h: 250, name: 'Kitchen' },
    ],
  },
  {
    id: 'almirah',
    title: 'Steel almirah to the first floor',
    blurb: 'A dog-legged Indian staircase with a mid landing and a sloping waist slab overhead.',
    icon: 'it-wardrobe',
    item: { type: 'wardrobe', params: { W: 91, H: 198, D: 51 } },
    route: [
      { t: 'door', w: 100, h: 210, d: 20 },
      { t: 'hall', w: 150, l: 220, h: 300 },
      { t: 'stairs', dir: 'up', w: 105, n: 10, rise: 16, go: 27, head: 205, ceil: 'sloped' },
      { t: 'turn', dir: 'UR', divider: 'wall' },
      { t: 'stairs', dir: 'up', w: 105, n: 10, rise: 16, go: 27, head: 205, ceil: 'sloped' },
      { t: 'hall', w: 150, l: 200, h: 300 },
      { t: 'door', w: 90, h: 210, d: 20 },
      { t: 'room', w: 360, l: 400, h: 300, name: 'Bedroom' },
    ],
  },
  {
    id: 'piano',
    title: 'Upright piano, no tipping',
    blurb: 'Pianos travel upright. A hallway, a turn and one more door.',
    icon: 'it-piano',
    item: { type: 'piano', params: { W: 150, H: 122, D: 55, keyD: 15, keyY: 62, layDown: false } },
    route: [
      { t: 'door', w: 91, h: 205, d: 14 },
      { t: 'hall', w: 120, l: 300, h: 260 },
      { t: 'turn', dir: 'L' },
      { t: 'door', w: 86, h: 205, d: 12 },
      { t: 'room', w: 420, l: 450, h: 270, name: 'Living room' },
    ],
  },
];

export const DEFAULT_EXAMPLE = 'front-door';
